import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../config/app_theme.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.backgroundColor,
      appBar: AppBar(
        title: Text(
          'Terms & Conditions',
          style: GoogleFonts.poppins(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: AppTheme.textColor,
          ),
        ),
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 18, color: AppTheme.textColor),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header Badge
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
              decoration: BoxDecoration(
                color: AppTheme.primaryColor.withOpacity(0.1),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(Icons.gavel_rounded, size: 14, color: AppTheme.primaryColor),
                  const SizedBox(width: 6),
                  Text(
                    'Legal & Governance',
                    style: GoogleFonts.poppins(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: AppTheme.primaryColor,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),

            Text(
              'Terms & Conditions',
              style: GoogleFonts.poppins(
                fontSize: 24,
                fontWeight: FontWeight.w800,
                color: AppTheme.textColor,
              ),
            ),
            const SizedBox(height: 4),

            Row(
              children: [
                const Icon(Icons.schedule_rounded, size: 14, color: AppTheme.subtitleColor),
                const SizedBox(width: 4),
                Text(
                  'Last Updated: September 28, 2026',
                  style: GoogleFonts.poppins(
                    fontSize: 12,
                    color: AppTheme.subtitleColor,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),
            const Divider(),
            const SizedBox(height: 16),

            _buildSection(
              title: '1. Introduction & Acceptance of Terms',
              content:
                  'Welcome to JoyEvents / Eventoza. By creating an account, booking an event or service, or accessing our platform, you agree to be bound by these Terms & Conditions. If you disagree with any part of these terms, you must not access or use the application.',
            ),
            _buildSection(
              title: '2. Platform Marketplace Role',
              content:
                  'JoyEvents acts as a digital marketplace connecting customers with verified independent merchants, event organizers, and service providers. Unless explicitly stated on a specific event listing, contracts for event admission or service performance are formed directly between the Customer and the respective Merchant.',
            ),
            _buildSection(
              title: '3. Account Registration & Security',
              content:
                  'Users must provide accurate, complete information during registration. You are responsible for maintaining the confidentiality of your account credentials. You must be at least 18 years of age or possess legal guardian consent to register or initiate paid bookings.',
            ),
            _buildSection(
              title: '4. Customer Accounts & Bookings',
              content:
                  'Customers are responsible for reviewing event details, venue rules, pricing, dates, and times before completing a booking. Valid digital tickets or QR codes generated by the app must be presented at the venue for scanning and admission.',
            ),
            _buildSection(
              title: '5. Merchant Obligations',
              content:
                  'Merchants listing events or services warrant that all listing details are truthful and compliant with local laws, permits, and safety regulations. Merchants agree to honor valid tickets and service appointments booked through the platform.',
            ),
            _buildSection(
              title: '6. Pricing, Payments & Wallet',
              content:
                  'All pricing is stated in Indian Rupees (₹). The in-app JoyEvents Wallet allows credited funds to be applied toward bookings. Merchants can request payout withdrawals to verified UPI IDs or bank accounts subject to administrative verification.',
            ),
            _buildSection(
              title: '7. Cancellations & Refund Policy',
              content:
                  'Refund eligibility is determined by merchant cancellation terms and platform rules. In the event of event cancellation by the organizer or platform admin, customers are entitled to a full refund or wallet store credit.',
            ),
            _buildSection(
              title: '8. Prohibited Conduct',
              content:
                  'Users shall not post fraudulent listings, attempt offline payments to bypass platform protections, scrape data, or compromise platform servers or user accounts.',
            ),
            _buildSection(
              title: '9. Intellectual Property',
              content:
                  'All platform logos, UI components, codebase, and branding belong to JoyEvents. User-uploaded media remains the property of the creator, granting JoyEvents a license for platform operation.',
            ),
            _buildSection(
              title: '10. Termination & Governing Law',
              content:
                  'JoyEvents reserves the right to suspend or terminate accounts violating these terms. These terms are governed by applicable local jurisdiction laws.',
            ),
            _buildSection(
              title: '11. Support & Contact',
              content:
                  'For questions regarding these Terms & Conditions, please contact us at info@eventoza.com.',
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }

  Widget _buildSection({required String title, required String content}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: GoogleFonts.poppins(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: AppTheme.textColor,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            content,
            style: GoogleFonts.poppins(
              fontSize: 13,
              color: AppTheme.textColor.withOpacity(0.85),
              height: 1.55,
            ),
          ),
        ],
      ),
    );
  }
}
